// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOq1bD-JF41gV2QgnuOEJFlzjuvAEa7kY',
    appId: '1:228695136206:web:cbd74e7b9924dcb6577d9f',
    messagingSenderId: '228695136206',
    projectId: 'tutor-ia-upec-ec787',
    authDomain: 'tutor-ia-upec-ec787.firebaseapp.com',
    storageBucket: 'tutor-ia-upec-ec787.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHtE3cOfZOCdvpSWeGAP7-VRis57V_-Fo',
    appId: '1:228695136206:android:120d4ec5ba789d32577d9f',
    messagingSenderId: '228695136206',
    projectId: 'tutor-ia-upec-ec787',
    storageBucket: 'tutor-ia-upec-ec787.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTfcrPvJjxx9Of9tF9RA7XvHif1KD066o',
    appId: '1:228695136206:ios:5aaf336196849bab577d9f',
    messagingSenderId: '228695136206',
    projectId: 'tutor-ia-upec-ec787',
    storageBucket: 'tutor-ia-upec-ec787.firebasestorage.app',
    iosClientId: '228695136206-heo9l32ph2pqgsms972pnve8oa5cem3a.apps.googleusercontent.com',
    iosBundleId: 'ec.edu.upec.tutornormativas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTfcrPvJjxx9Of9tF9RA7XvHif1KD066o',
    appId: '1:228695136206:ios:5aaf336196849bab577d9f',
    messagingSenderId: '228695136206',
    projectId: 'tutor-ia-upec-ec787',
    storageBucket: 'tutor-ia-upec-ec787.firebasestorage.app',
    iosClientId: '228695136206-heo9l32ph2pqgsms972pnve8oa5cem3a.apps.googleusercontent.com',
    iosBundleId: 'ec.edu.upec.tutornormativas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOq1bD-JF41gV2QgnuOEJFlzjuvAEa7kY',
    appId: '1:228695136206:web:27af78692653b9db577d9f',
    messagingSenderId: '228695136206',
    projectId: 'tutor-ia-upec-ec787',
    authDomain: 'tutor-ia-upec-ec787.firebaseapp.com',
    storageBucket: 'tutor-ia-upec-ec787.firebasestorage.app',
  );
}
